services:
  manga_pgvector:
    container_name: manga_pgvector
    image: ankane/pgvector
    ports:
      - ${DB_PORT}:5432
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"